In [1]:
import pandas as pd 
import matplotlib.pyplot as plt

In [ ]:
# Por cuestiones de tamaño no se puede usar este archivo

# tabla1 = pd.read_csv("US_Accidents_March23.csv")
# tabla1.head()

In [ ]:
# %%time
# total_severity_three = (tabla1["Severity"] == 3).sum()
# print(total_severity_three)

In [ ]:
# %%time
# tabla1.isnull().sum()

In [3]:
tabla2 = pd.read_csv("../data/winemag-data-130k-v2.csv")
tabla2.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [4]:
%%time
italy_total = (tabla2["country"] == "Italy").sum()
print(italy_total)

19540
CPU times: user 35.1 ms, sys: 3.01 ms, total: 38.1 ms
Wall time: 41 ms

In [6]:
%%time
tabla2.isnull().sum()

CPU times: user 156 ms, sys: 985 μs, total: 157 ms
Wall time: 210 ms

Unnamed: 0                   0
country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

In [7]:
tabla3 = pd.read_csv("../data/customer_master.csv")
tabla3.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

In [8]:
%%time
vip_total = (tabla3["customer_segment"] == "VIP").sum()
print(vip_total)

2542
CPU times: user 10.9 ms, sys: 2.88 ms, total: 13.8 ms
Wall time: 12.4 ms

In [9]:
%%time
tabla3.isnull().sum()

CPU times: user 44.9 ms, sys: 5.54 ms, total: 50.5 ms
Wall time: 50 ms

customer_id                  0
customer_name                0
customer_age                 0
gender                       0
customer_segment             0
customer_city                0
customer_state               0
customer_country             0
region                       0
customer_postal_code         0
customer_acquisition_cost    0
dtype: int64

In [12]:
tabla2.shape

(129971, 14)

In [13]:
tabla3.shape

(25000, 11)